### ISSUE TITLE
간단 글쓰기에서 사진 첨부시 작성 버튼이 비활성화 됩니다.

### ISSUE THREAD

**Issue by LiteHell** [koreapyj/dcinside_lite#10]
![스크린샷](https://cloud.githubusercontent.com/assets/12497886/9105695/18cff8ec-3c55-11e5-8387-0f27b6c35aed.PNG)

File버튼을 눌러 사진을 선택하고 첨부한 모습입니다 (첨부가 된건지 아닌지도 모르겠지만)
사용 환경 : Firefox 39.0 / Greasemonkey 3.3
DCinside Lite 버전 : r15010

**Comment by koreapyj** [comment]
업로드 중에는 원래 작성 버튼을 누를 수 없게 됩니다.

**Comment by LiteHell** [comment]
7.10KB짜리 사진을 업로드하는 데 5~6분이 지나도 무소식인데요... (지금도 무소식, 버튼 활성화 안됨)
인터넷 속도는 정상입니다. ([인터넷 속도측정 결과](http://www.speedtest.net/my-result/4561198002))

**Comment by koreapyj** [comment]
지금 해보니까 되다가 안되다가 하네요

**Comment by koreapyj** [comment]
dfe73d32d6 에서도 그러나요?

**Comment by LiteHell** [comment]
글쎄요, 지금 컴퓨터를 사용할 수 없으니 나중에 확인할께요.
2015. 8. 6. 오후 5:07에 "koreapyj" <notifications@github.com>님이 작성:

**Comment by LiteHell** [comment]
커밋 dfe73d3 (현재 Git저장소에 있는 최신 버전) 설치해서 시도해봤고요, 안됩니다. 2분이 지나도 안됩니다.

**Comment by koreapyj** [comment]
확인했습니다. Firefox 37에서는 정상적으로 업로드가 되는데 이상하게 39에서 안되네요. 좀 더 조사를 해봐야 될 것 같군요.

**Comment by koreapyj** [comment]
Gecko 31부터 XMLHTTPRequest의 sendAsBinary를 사용할 수 없게 되었는데 GreaseMonkey에서 binary로 전송하게 하면 이걸 사용하기 때문에 문제가 생긴 것 같습니다.

**Comment by LiteHell** [comment]
지금은 해결됬는데(잘 작동합니다) 안 닫나요?

**Comment by LiteHell** [comment]
지금은 해결됬으니까 닫을께요.
