### ISSUE TITLE
메뉴바에서 다른갤러리로이동할경우 이전갤러리의 일베/개념글이 그대로 화면 상단에 남아있습니다

### ISSUE THREAD

**Issue by headcrabtan** [koreapyj/dcinside_lite#16]
보통 자주다니는갤러리의 링크를 메뉴바에 저장해두고 이리저리돌아다니는편인데 어느순간부터 다른갤러리로 이동해도 화면상단의 개념글/일베가 이전 갤러리의 것으로 고정되어있고 또 글쓰기버튼을 눌러도 이동하기 전 갤러리 글쓰기로 넘어가지던데 혹시 수정가능할까요?

**Comment by koreapyj** [comment]
일베가 없어졌습니다. + 개념글은 언제부턴가 고쳐졌습니다.
