### ISSUE TITLE
게시글 클릭이 안 됩니다.

### ISSUE THREAD

**Issue by A2ku** [koreapyj/dcinside_lite#18]
윈도우 8.1
크롬 버전 48.0.2564.103 m

대체로 해당 페이지의 4개글 까지는 클릭이 되지만 그 밑으로는 마우스 커서 모양 조차도 바뀌지 않습니다.
휠 스크롤을 움직이면 클릭 될 때도 있고 안 될때도 있습니다. 매 순간 다릅니다.

글쓰기나 전체글 보니 개념글 같은 버튼은 제대로 클릭이 되지만 게시글만 클릭이 안 됩니다.

**Comment by koreapyj** [comment]
좀 더 좋은 애드블록 확장기능을 쓰세요
